config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'offers#index'
  resources :offers, only: %i[index show]
end

app/models/admin_user.rb
# frozen_string_literal: true

# Model AdminUser
class AdminUser < ApplicationRecord
  has_secure_password
  validates :username, uniqueness: true, format: { without: /\s/ }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/offer.rb
# frozen_string_literal: true

# Model offer
class Offer < ApplicationRecord
  validates :company, presence: true
  validates :advertiser_name, presence: true
  validates :description, presence: true, length: { maximum: 500 }
  validates :url, presence: true, format: { with: /\A(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?\z/ix  }
  validates :starts_at, presence: true
  validate :ends_after_starts_at?, if: -> { ends_at && starts_at }

  enum status: %i[disabled enabled]

  scope :enabled, -> {
    where(status: 'enabled')
      .where(':date BETWEEN starts_at AND ends_at OR starts_at < :date AND ends_at is NULL', date: Time.zone.now)
  }

  private

  def ends_after_starts_at?
    return if ends_at > starts_at

    errors.add :end_date, 'must be after start date'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def home; end

  protected

  def authenticate_admin_user!
    try_authenticate_admin || request_authenticate_admin
  end

  def try_authenticate_admin
    authenticate_with_http_basic do |username, password|
      admin_user = AdminUser.find_by_username(username)
      admin_user&.authenticate(password)
    end
  end

  def request_authenticate_admin
    request_http_basic_authentication
  end
end

app/controllers/offers_controller.rb
# frozen_string_literal: true

# Offers controller
class OffersController < ApplicationController
  before_action :set_offers, only: :index
  protect_from_forgery except: :index

  def index
    respond_to do |format|
      format.js
      format.html
    end
  end

  private

  def set_offers
    if params[:premium]
      offers = Offer.enabled.where(premium: true)
    else
      offers = Offer.enabled
    end

    @offers = offers.page(params[:page])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/application/home.html.erb
<section id="offers">
  <div class="card-columns">
    <div class="card rounded text-center">
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This card has a regular title and short paragraphy of text below it.</p>
        <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OfferApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render partial: './layouts/partials/navbar' %>
    <div class="container">
      <%= render partial: './layouts/partials/jumbotron' %>
      <div class="tabs rounded">
        <%= link_to offers_path, remote: true do %>
          <span> All</span>
        <% end %>
        <%= link_to offers_path(premium: true), id: "teste", remote: true do %>
          <span> Premium</span>
        <% end %>
      </div>
      <%= yield %>
      <%= render partial: './layouts/partials/footer' %>
    </div>
  </body>
</html>

app/views/layouts/partials/_footer.html.erb
<footer class="pt-4 my-md-5 pt-md-5 border-top">
  <div class="row">
    <div class="col-12 col-md">
      <img class="mb-2" src="../../assets/brand/bootstrap-solid.svg" alt="" width="24" height="24">
      <small class="d-block mb-3 text-muted">© 2017-2018</small>
    </div>
    <div class="col-6 col-md">
      <h5>Features</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Cool stuff</a></li>
        <li><a class="text-muted" href="#">Random feature</a></li>
        <li><a class="text-muted" href="#">Team feature</a></li>
        <li><a class="text-muted" href="#">Stuff for developers</a></li>
        <li><a class="text-muted" href="#">Another one</a></li>
        <li><a class="text-muted" href="#">Last time</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>Resources</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Resource</a></li>
        <li><a class="text-muted" href="#">Resource name</a></li>
        <li><a class="text-muted" href="#">Another resource</a></li>
        <li><a class="text-muted" href="#">Final resource</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>About</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Team</a></li>
        <li><a class="text-muted" href="#">Locations</a></li>
        <li><a class="text-muted" href="#">Privacy</a></li>
        <li><a class="text-muted" href="#">Terms</a></li>
      </ul>
    </div>
  </div>
</footer>

app/views/layouts/partials/_jumbotron.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container" id="container-jumbotron">
    <h1 id="title" class="display-3">YOU</h1>
    <h2 >Shop</h2>
    <h2 >Get</h2>
    <h2 >Save</h2>
    <h1  id="footer" >More.</h1>
  </div>
</div>

app/views/layouts/partials/_navbar.html.erb
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">
    <img src="lemoney-logo.png" width="auto" height="40" alt="">
  </a>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <a class="nav-link" href="#">About <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Contact us</a>
      </li>
    </ul>
    <div class="nav-item">
        <a class="nav-link" href="#" tabindex="-1" aria-disabled="true">Log in</a>
    </div>
  </div>
</nav>

app/views/offers/index.html.erb
<section id="offers">
  <div class="card-columns">
    <%= render partial: './offers/partials/offers' %>
  </div>
  <%= paginate @offers %>
</section>

<script>
  function countDown(date, id) {
    console.log(date);
    if (date == '') { return; }
    setInterval(function() {
      var now = new Date().getTime();
      var expireDate = new Date(date).getTime();

      var left = expireDate - now;

      var days = Math.floor(left / (1000 * 60 * 60 * 24));
      var hours = Math.floor((left % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
      var minutes = Math.floor((left % (1000 * 60 * 60)) / (1000 * 60));
      var seconds = Math.floor((left % (1000 * 60)) / 1000);

      if (left < 0) {
        clearInterval(x);
        document.getElementById(id).innerHTML = "EXPIRED";
      }

      document.getElementById(id).innerHTML = "Expires in " + days + "d " + hours + "h "
      + minutes + "m " + seconds + "s ";
    },1000);
  };
</script>

app/views/offers/index.js.erb
$(".card-columns")
  .fadeOut(300, function(){
    $(this).html(
      "<%= escape_javascript(render partial: './offers/partials/offers',
        locals: { offers: @offers })%>"
    );
  }).fadeIn(300);

app/views/offers/partials/_offers.html.erb
<% @offers.each do |offer|%>
  <div class="card text-center" onmouseover="countDown('<%=offer.ends_at&.strftime('%a %b %e %T %Y')%>', '<%= offer.id %>')">
    <% if offer.premium%>
      <span class="badge right">Premium</span>
    <%end%>
    <div class="card-header">
      <img src="http://icons.iconarchive.com/icons/grafikartes/flat-retro-modern/256/rainbow-apple-logo-icon.png" width="auto" height="60" alt="">
    </div>
    <div class="card-body">
      <h5 class="card-title"><%= offer.advertiser_name %></h5>
      <p class="card-text"><%= offer.company %></p>
      <a target="_blank" href="<%= offer.url %>" class="takeit btn">Take it!</a>
    </div>
    <div class="card-footer text-muted">
      <span id="<%=offer.id%>">
        Expires at <%= offer.ends_at&.strftime('%a %b %e %T %Y') %>
      </span>
    </div>
  </div>
<%end%>